# Generated by Django 3.2.8 on 2021-11-21 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_shopuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagLine', models.CharField(blank=True, max_length=128, verbose_name='Тэги')),
                ('about_me', models.TextField(verbose_name='Обо мне')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский'), ('O', 'Иное')], default='O', max_length=1, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
